# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'email_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import json
import sqlite3

import requests
from PyQt5 import QtCore, QtGui, QtWidgets

from email_sent_dialog import Ui_email_sent_Dialog


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(442, 159)
        self.Dialog = Dialog
        self.submit_key = QtWidgets.QPushButton(Dialog)
        self.submit_key.setGeometry(QtCore.QRect(340, 98, 75, 24))
        self.submit_key.setObjectName("submit_key")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(30, 10, 311, 61))
        self.label_4.setOpenExternalLinks(True)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 103, 47, 13))
        self.label_3.setObjectName("label_3")
        self.name = QtWidgets.QLineEdit(Dialog)
        self.name.setGeometry(QtCore.QRect(80, 100, 221, 20))
        self.name.setObjectName("name")
        self.submit_key.clicked.connect(self.open_email_sent_dialog)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def open_email_sent_dialog(self):
        email = self.name.text()
        # add email to database
        con = sqlite3.connect('autoclicker.db')
        cursor = con.cursor()
        email_data = (email,)
        cursor.execute("UPDATE local_table SET email = ?", email_data)
        con.commit()
        print("adding email to local database")
        con.close()

        # call api to send verification email
        # Making a POST request
        response2 = requests.post('https://auth-provider.onrender.com/register', data={"email": email})
        print(response2.text)
        print(type(response2.text))
        json_message = json.loads(response2.text)
        print("verification mail sent")
        if json_message["message"] == "Email sent":
            print("here")
            self.Dialog.hide()
            self.dialog = QtWidgets.QDialog()
            self.ui = Ui_email_sent_Dialog()
            self.ui.setupUi(self.dialog, email)
            self.dialog.show()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Email Verification"))
        self.submit_key.setText(_translate("Dialog", "Submit"))
        self.label_4.setText(_translate("Dialog", "Please provide your email id, and click on submit. \n"
"you will receive a verification link on your email, \n"
"click on it to continue using the app unobstructed."))
        self.label_3.setText(_translate("Dialog", "Email:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
