# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'enter_license_key.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_license_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(442, 159)
        self.enter_key = QtWidgets.QPushButton(Dialog)
        self.enter_key.setGeometry(QtCore.QRect(340, 120, 75, 23))
        self.enter_key.setObjectName("enter_key")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 10, 311, 41))
        self.label.setOpenExternalLinks(True)
        self.label.setObjectName("label")
        self.name = QtWidgets.QLineEdit(Dialog)
        self.name.setGeometry(QtCore.QRect(90, 67, 221, 20))
        self.name.setObjectName("name")
        self.licensekey = QtWidgets.QLineEdit(Dialog)
        self.licensekey.setGeometry(QtCore.QRect(90, 100, 221, 20))
        self.licensekey.setObjectName("licensekey")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 95, 61, 31))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Enter License Key"))
        self.enter_key.setText(_translate("Dialog", "Submit"))
        self.label.setText(_translate("Dialog", "Please enter username and license key below, \n"
"exactly as provided by the GG team post successful subscription"))
        self.label_2.setText(_translate("Dialog", "Name"))
        self.label_3.setText(_translate("Dialog", "License Key"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_license_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
