# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'payment_dialogue.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from license_dialog import Ui_license_Dialog

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(442, 159)
        self.enter_key = QtWidgets.QPushButton(Dialog)
        self.enter_key.clicked.connect(self.open_license_dialog)
        self.enter_key.setGeometry(QtCore.QRect(190, 117, 75, 23))
        self.enter_key.setObjectName("enter_key")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 10, 371, 91))
        self.label.setOpenExternalLinks(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(26, 92, 231, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 44, 111, 20))
        self.label_3.setStyleSheet("color: blue")
        self.label_3.setOpenExternalLinks(True)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def open_license_dialog(self):
        self.dialog = QtWidgets.QDialog()
        self.ui = Ui_license_Dialog()
        self.ui.setupUi(self.dialog)
        self.dialog.show()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "GG Plus subscription"))
        self.enter_key.setText(_translate("Dialog", "Enter Key..."))
        self.label.setText(_translate("Dialog", "Click on the link below to visit GG autoclicker\'s purchase page: \n"
"\n"
"\n"
"Post successful payment, you will get a username and license key."))
        self.label_2.setText(_translate("Dialog", " Click \"Enter Key\" to register them."))
        self.label_3.setText(_translate("Dialog", "<a href='https://autoclicker.gg/'>https://autoclicker.gg/"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
